volumes:
  prometheus-data:
  grafana-data:
#  pyroscope-data:

services:
  express_service:
    container_name: node_container
    image: node_express:v1.0.0
    # stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
      target: program
    environment:
      - PORT=3000
      - NODE_ENV=production
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/usr/src:ro

#  pyroscope:
#    container_name: grafana-pyroscope
#    image: grafana/pyroscope
#    ports:
#      - 4040:4040
#    environment:
#      - PYROSCOPE_CONFIG=/etc/pyroscope/config.yml
#      - PYROSCOPE_LOG_LEVEL=debug # Log level set as environment variable
#      - PYROSCOPE_STORAGE_PATH=/var/lib/pyroscope # Storage path as environment variable
#      - PYROSCOPE_STORAGE_RETENTION=7d # Retention as environment variable
#    volumes:
#      - ./pyroscope.yml:/etc/pyroscope/config.yml:ro
#      - pyroscope-data:/var/lib/pyroscope:rw

  prometheus:
    container_name: prometheus-server
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - prometheus-data:/prometheus:rw
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro

  grafana:
    container_name: grafana-server
    image: grafana/grafana-enterprise
    environment:
      - GF_INSTALL_PLUGINS=grafana-pyroscope-app
    ports:
      - 5000:3000
    volumes:
      - grafana-data:/var/lib/grafana:rw
