global:
  scrape_interval: 15s
  scrape_timeout: 15s

scrape_configs:
  - job_name: 'express-application'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['express_service:3000']
