networks:
  jenkins:

volumes:
  jenkins-data:

services:
  jenkins-server:
    container_name: jenkis-blueocean
    image: jenkins/jenkins
    networks:
      - jenkins
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - jenkins-data:/var/jenkins_home
# user=roshan, password=roshan
