volumes:
  mongodata:
services:
  mongodb:
    image: mongo
    container_name: mongo-db-container
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
    volumes:
      - mongodata:/data/db
