version: "3"

services:
  reverse-proxy:
    image: traefik:v2.4
    command:
      - --providers.docker
      - --providers.docker.exposedbydefault=false
      # create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # enable the access log, with http requests
      - --accesslog
      #   enable the trafik log, for configurations and errors
      - --log
      # Enable the DASHBOARD  and API
      - --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 80:80
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.traefik-dashboard.loadbalancer.server.port=8080
      - traefik.http.routers.traefik-dashboard-http.entrypoints=http
      - traefik.http.routers.traefik-dashboard-http.rule=Host(`traefik-dashboard.docker.localhost`)
      - traefik.http.routers.traefik-dashboard-http.service=api@internal
      - traefik.http.middlewares.admin-auth.basicauth.users=user1:$apr1$rqck0rds$YerU1IElUf3P/UlbvwzQ4.
      - traefik.http.routers.traefik-dashboard-http.middlewares=admin-auth
    networks:
      - traefik-public
    restart: always

  whoami:
    image: traefik/whoami
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-public
      - traefik.http.services.whoami.loadbalancer.server.port=80
      - traefik.http.routers.whoami-http.entrypoints=http
      - traefik.http.routers.whoami-http.rule=Host(`whoami.docker.localhost`)
    networks:
      - traefik-public
    restart: always

networks:
  traefik-public:
    external: true
