services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
    # enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
     - DOZZLE_ENABLE_ACTIONS=true
    # allow access to container shells. See https://dozzle.dev/guide/shell
     - DOZZLE_ENABLE_SHELL=true
    # enable authentication. See https://dozzle.dev/guide/authentication
    # - DOZZLE_AUTH_PROVIDER=simple